//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatPrivateMessageDetail
    {
        public int ID { get; set; }
        public string MasterEmailID { get; set; }
        public string ChatToEmailID { get; set; }
        public string Message { get; set; }
    }
}
